### PR TITLE
fix php 8 errors when data is null

### PR DESCRIPTION
**Pull request by BeardTech**

### CODE REVIEW

**Comment by thedotwriter** [comment]
Hi @BeardTech, did you test this out on a Magento 2.4.5? Is this small fix enough to make things work on PHP 8.1?

Cheers

**Comment by BeardTech** [comment]
@thedotwriter Exactly it works on my production right now with this fix.

**Comment by thedotwriter** [comment]
Thanks for the quick feedback! We'll try this out then : )

**Comment by gthomas-lengow** [comment]
in production

**Pull request closed without merging**
